# Generated by Django 6.0.7 on 2026-07-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
