# Generated by Django 6.0.7 on 2026-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_school_class_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='role_type',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian')], default='guardian', max_length=10),
            preserve_default=False,
        ),
    ]
