# Generated by Django 6.0.7 on 2026-10-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academics.assignment'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school_classes',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='termperformancereport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_performance_reports', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='termperformancereport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_term_performance_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='academics_a_date_622e79_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['school_class', 'date'], name='academics_a_school__63f677_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='academics_a_student_ec0522_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_student_attendance_per_day'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'subject', 'school_class', 'term', 'session')},
        ),
        migrations.AddConstraint(
            model_name='termperformancereport',
            constraint=models.UniqueConstraint(fields=('student', 'term', 'session'), name='unique_student_term_performance_report'),
        ),
    ]
