# Generated by Django 6.0.7 on 2026-07-30 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0002_alter_student_admission_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='school_class',
        ),
        migrations.AddField(
            model_name='subject',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'subject', 'school_class')},
        ),
    ]
