# Generated by Django 6.0.7 on 2026-08-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_subject_school_class_subject_grades_and_more'),
        ('accounts', '0004_parent_role_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examresult',
            name='session',
            field=models.CharField(default=2026, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='school_classes',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.schoolclass'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'subject', 'school_class', 'term', 'session')},
        ),
    ]
